### ISSUE TITLE
Exporting on chrome asks for my PC user password

### ISSUE THREAD

**Issue by CarlosBermudez** [Guereak/USBDuckyScripts#4]
Hi! Whenever it goes to "Export Passwords" I get a windows prompt to put my computer password and if I do it then it lets me save the file.

Is there any way of disabling that prompt beforehand so I can export it?

This is the prompt (sorry it is in spanish)
![073561aa6bbdfc4c2e921b4b110f47a5](https://user-images.githubusercontent.com/1471868/135931009-44e1ebf5-74be-44f9-8bbd-3d123cbef5de.png)

Thanks

**Comment by MaximeLglr** [comment]
Because of a recent security update, it appears that the file cannot be created if the device you are trying to run this on a device with a password or any form of biometric authentication. (too good to be true otherwise)
Therefore this script will now only work on devices that doesn't require a password to login. If the script isn't working either for you on those, you may want to try adding 2 more lines as explained in the README file.
